language: python
addons:
  postgresql: 9.3
before_install:
 - node --version
install:
 - make env node_modules
 - pip install coveralls
before_script:
 - echo "${TRAVIS_BRANCH}"
 - echo "`git rev-parse --abbrev-ref HEAD`"
 - echo "DATABASE_URL=dbname=gratipay" | tee -a tests/local.env local.env
 - psql -U postgres -c 'CREATE DATABASE "gratipay";'
 - if [ "`git rev-parse --abbrev-ref HEAD`" = "master" ]; then rm -rf tests/fixtures; fi
script: make test
after_success:
  coveralls
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#gratipay"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true
